//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplyNowWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    using Microsoft.Azure.Documents;
    using Newtonsoft.Json;

    public partial class Device : Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.ComplianceResponses = new HashSet<ComplianceResponse>();
        }

        [JsonProperty(PropertyName = "UniqueId")]
        public string UniqueId { get; set; }

        [JsonProperty(PropertyName = "DeviceType")]
        public string DeviceType { get; set; }

        [JsonProperty(PropertyName = "HardwareVersion")]
        public string HardwareVersion { get; set; }

        [JsonProperty(PropertyName = "FirmwareVersion")]
        public string FirmwareVersion { get; set; }

        [JsonProperty(PropertyName = "PatientId")]
        public int PatientId { get; set; }

        [JsonProperty(PropertyName = "CreatedDateTime")]
        public DateTime CreatedDateTime { get; set; }

        [JsonProperty(PropertyName = "UpdatedDateTime")]
        public DateTime UpdatedDateTime { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [JsonProperty(PropertyName = "ComplianceResponses")]
        public virtual ICollection<ComplianceResponse> ComplianceResponses { get; set; }
    }
}
